### ISSUE TITLE
Postcode is missing

### ISSUE THREAD

**Issue by jutikorn** [ignitry/thai-tambons#3]
มี Postcode มั้ยครับ

**Comment by wittawasw** [comment]
มี แต่ไม่ครบครับ อยู่ในไฟล์ dist/tambons ตรง zipcode ถ้าตรงนั้นเว้นว่างคือไม่มีข้อมูล
ผมเองยังไม่ได้ใช้ เลยไม่ได้หามาใส่เพิ่มให้ครบ
